### ISSUE TITLE
error: RoonServer: /usr/lib/libstdc++.so.6: no version information available

### ISSUE THREAD

**Issue by haysclark** [josepba/dockerroonserver#3]
Roon is no longer starting after a recent update. Looks like there is a library that is missing.

```bash
~ sudo docker run --name roon \                                                                                                                                                               master 305a899 ✗
                --net=host \
                -v /var/roon:/var/roon \
                -v /opt/RoonStuff:/opt/RoonStuff\
                -v /mnt/music:/music \
                -v /mnt/backup:/backup \
                josepba/roonserver
/opt/RoonStuff/RoonServer/RoonDotnet/RoonServer: /usr/lib/libstdc++.so.6: no version information available (required by /opt/RoonStuff/RoonServer/RoonDotnet/RoonServer)
/opt/RoonStuff/RoonServer/RoonDotnet/RoonServer: /usr/lib/libstdc++.so.6: no version information available (required by /opt/RoonStuff/RoonServer/RoonDotnet/RoonServer)
/opt/RoonStuff/RoonServer/RoonDotnet/RoonServer: /usr/lib/libstdc++.so.6: no version information available (required by /opt/RoonStuff/RoonServer/RoonDotnet/RoonServer)
/opt/RoonStuff/RoonServer/RoonDotnet/RoonServer: /usr/lib/libstdc++.so.6: no version information available (required by /opt/RoonStuff/RoonServer/RoonDotnet/RoonServer)
/opt/RoonStuff/RoonServer/start.sh: line 52:    10 Segmentation fault      (core dumped) "$P" "$@"
/opt/RoonStuff/RoonServer/start.sh: line 34: kill: (10) - No such process
```

**Comment by haysclark** [comment]
If I build the docker image and run that I get a more detailed log, but it still appears to be related to glibc.

```
sudo docker run --name roon \                                                                                                                                                               master 565c9b5 ✗
                --net=host \
                -v /var/roon:/var/roon \
                -v /opt/RoonStuff:/opt/RoonStuff\
                -v /mnt/music:/music \
                -v /mnt/backup:/backup \
                13373c76b6da
/opt/RoonStuff/RoonServer/RoonDotnet/RoonServer: /usr/lib/libstdc++.so.6: no version information available (required by /opt/RoonStuff/RoonServer/RoonDotnet/RoonServer)
/opt/RoonStuff/RoonServer/RoonDotnet/RoonServer: /usr/lib/libstdc++.so.6: no version information available (required by /opt/RoonStuff/RoonServer/RoonDotnet/RoonServer)
/opt/RoonStuff/RoonServer/RoonDotnet/RoonServer: /usr/lib/libstdc++.so.6: no version information available (required by /opt/RoonStuff/RoonServer/RoonDotnet/RoonServer)
/opt/RoonStuff/RoonServer/RoonDotnet/RoonServer: /usr/lib/libstdc++.so.6: no version information available (required by /opt/RoonStuff/RoonServer/RoonDotnet/RoonServer)
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
realpath(/opt/RoonStuff/RoonServer/RoonDotnet/shared/Microsoft.NETCore.App/5.0.0/) failed: Operation not permitted
Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at System.Number.<TryFormatInt32>g__TryFormatInt32Slow|39_0(Int32, Int32, System.ReadOnlySpan`1<Char>, System.IFormatProvider, System.Span`1<Char>, Int32 ByRef)
   at System.Number.TryFormatInt32(Int32, Int32, System.ReadOnlySpan`1<Char>, System.IFormatProvider, System.Span`1<Char>, Int32 ByRef)
   at System.Int32.TryFormat(System.Span`1<Char>, Int32 ByRef, System.ReadOnlySpan`1<Char>, System.IFormatProvider)
   at System.Text.ValueStringBuilder.AppendFormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
   at System.String.FormatHelper(System.IFormatProvider, System.String, System.ParamsArray)
   at System.String.Format(System.String, System.Object[])
   at Base.ColorConsoleLogWriter._FormatTime()
   at Base.ColorConsoleLogWriter._Write(System.String, System.String, System.String)
   at Base.ColorConsoleLogWriter.WriteWarning(System.String)
   at Base.Log.WriteWarning(System.String)
   at Base.Log.WriteWarning(System.String, System.Object[])
   at Sooloos.Utils.GetLockFile(System.String, Boolean ByRef)
   at Sooloos.App.GetAppLock()
   at Sooloos.App.Main(System.String[])
/opt/RoonStuff/RoonServer/start.sh: line 52:     9 Aborted                 (core dumped) "$P" "$@"
/opt/RoonStuff/RoonServer/start.sh: line 34: kill: (9) - No such process
```

**Comment by haysclark** [comment]
For those that don't want to be blocked, you can easily switch to [steefdebruijn/docker-roonserver](https://hub.docker.com/r/steefdebruijn/docker-roonserver) without any issues. 

Here is my old startup command for [josepba/roonserver](https://hub.docker.com/r/josepba/roonserver):

``` bash
# start a fresh Roon container
sudo docker run -d --name roon \
  --net=host \
  -v /var/roon:/var/roon \
  -v /opt/RoonStuff:/opt/RoonStuff\
  -v /mnt/music:/music \
  -v /mnt/backup:/backup \
  josepba/roonserver
```

Here is the equivalent for [steefdebruijn/docker-roonserver](https://hub.docker.com/r/steefdebruijn/docker-roonserver):

``` bash
# start a fresh Roon container
sudo docker run -d --name roon \
  --net=host \
  -e TZ="America/Los_Angeles" \
  -v /opt/RoonStuff:/app \
  -v /var/roon:/data \
  -v /mnt/music:/music \
  -v /mnt/backup:/backup \
  steefdebruijn/docker-roonserver:latest
```

**Comment by kumorid** [comment]
Hello Hays. Sorry for not answering this earlier, but I was no longer maintaining (or using) this docker image, as I am relying on a port of Roon Server to the QNAP NAS.

Thanks for posting instructions for using a different image, it may come in handy in the future.
